name: Application

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'current'
    
      - name: Install dependencies
        run: |
            cd app
            npm install
  
      - name: Run tests
        run: |
            cd app
            npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: app
          push: true
          tags: |
           georgeulahannan/devopassessment:latest
           georgeulahannan/devopassessment:${{ github.sha }}

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: georgeulahannan/devopassessment:${{ github.sha }}




  update-k8s-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: success()

    steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Set up Git configuration
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"

        - name: Checkout target repository
          uses: actions/checkout@v4
          with:
            ref: main
            repository: xmgeorge/sample-app  # Replace with your target repository
            token: ${{ secrets.MAINFEST_GITHUB_TOKEN }}
            path: k8s-manifests

        - name: Update Kubernetes manifest with new image tag
          run: |
            cd k8s-manifests # Change to the directory of the target repository
            sed -i "s|image: georgeulahannan/devopassessment:.*|image: georgeulahannan/devopassessment:${{ github.sha }}|g" k8s-manifests/deployment.yaml  # Update this path as necessary
            git add k8s-manifests/deployment.yaml  # Add the changed file
            git commit -m "Update image tag to ${{ github.sha }}"
            git push origin main