name: Terraform

on:
  push:
    paths:
      - 'tfscaffold/**'
  pull_request:
    paths:
      - 'tfscaffold/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    container:
      image: georgeulahannan/terraform:06
      options: --user root  # Ensure Terraform commands run with root user if needed
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Plan VPC
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p emis -c vpc -e dev -r us-east-1 -a plan
