name: Terraform

on:
  push:
    paths:
      - 'tfscaffold/**'
  pull_request:
    paths:
      - 'tfscaffold/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    container:
        image: georgeulahannan/terraform:07
        options: --user root
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        
      - name: Get branch name
        id: get_branch
        run: echo "::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/})"
    
      - name: Get build ID
        id: get_build_id
        run: echo "::set-output name=build_id::${GITHUB_RUN_ID}"

      - name: Teraform VPC Plan
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p emis -c vpc -i ${{ steps.get_build_id.outputs.build_id }} -e ${{ steps.get_branch.outputs.branch_name }} -r us-east-1 -a plan

      - name: Teraform EKS Plan
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p emis -c eks -i ${{ steps.get_build_id.outputs.build_id }} -e ${{ steps.get_branch.outputs.branch_name }} -r us-east-1 -a plan

      - name: Teraform EKSALB Plan
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p emis -c eksalb -i ${{ steps.get_build_id.outputs.build_id }} -e ${{ steps.get_branch.outputs.branch_name }} -r us-east-1 -a plan
      
      - name: Teraform EKSARGOCD Plan
        run: |
          cd tfscaffold
          ./bin/terraform.sh -p emis -c eksargocd -i ${{ steps.get_build_id.outputs.build_id }} -e ${{ steps.get_branch.outputs.branch_name }} -r us-east-1 -a plan
          


